In [1]:
!pip install featuretools[autonormalize]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting featuretools[autonormalize]
  Downloading featuretools-1.24.0-py3-none-any.whl (585 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 KB 6.6 MB/s eta 0:00:00
Requirement already satisfied: distributed!=2022.10.1,>=2022.2.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (2022.12.1)
Requirement already satisfied: psutil>=5.6.6 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (5.9.4)
Requirement already satisfied: dask[dataframe]!=2022.10.1,>=2022.2.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (2022.12.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (23.0)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (1.4.4)
Requirement already satisfied: cloudpickle>=1.5.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (2.2.1)
Requirement already satisfied: scipy>=1.4.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (1.10.1)
Requirement already satisfied: tqdm>=4.32.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (4.65.0)
Collecting woodwork[dask]>=0.18.0
  Downloading woodwork-0.22.0-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.8/232.8 KB 13.9 MB/s eta 0:00:00
Requirement already satisfied: holidays>=0.13 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (0.21.13)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.9/dist-packages (from featuretools[autonormalize]) (1.22.4)
Collecting autonormalize>=2.0.1
  Downloading autonormalize-2.0.1-py3-none-any.whl (612 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 612.3/612.3 KB 17.4 MB/s eta 0:00:00
Requirement already satisfied: graphviz>=0.8.4 in /usr/local/lib/python3.9/dist-packages (from autonormalize>=2.0.1->featuretools[autonormalize]) (0.20.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.9/dist-packages (from dask[dataframe]!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (8.1.3)
Requirement already satisfied: fsspec>=0.6.0 in /usr/local/lib/python3.9/dist-packages (from dask[dataframe]!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (2023.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.9/dist-packages (from dask[dataframe]!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (6.0)
Requirement already satisfied: partd>=0.3.10 in /usr/local/lib/python3.9/dist-packages (from dask[dataframe]!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (1.3.0)
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.9/dist-packages (from dask[dataframe]!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (0.12.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (1.26.15)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (1.0.0)
Requirement already satisfied: tornado>=6.0.3 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (6.2)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (1.7.0)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (2.2.0)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (1.0.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/dist-packages (from distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (3.1.2)
Requirement already satisfied: korean-lunar-calendar in /usr/local/lib/python3.9/dist-packages (from holidays>=0.13->featuretools[autonormalize]) (0.3.1)
Requirement already satisfied: PyMeeus in /usr/local/lib/python3.9/dist-packages (from holidays>=0.13->featuretools[autonormalize]) (0.5.12)
Requirement already satisfied: hijri-converter in /usr/local/lib/python3.9/dist-packages (from holidays>=0.13->featuretools[autonormalize]) (2.2.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from holidays>=0.13->featuretools[autonormalize]) (2.8.2)
Requirement already satisfied: convertdate>=2.3.0 in /usr/local/lib/python3.9/dist-packages (from holidays>=0.13->featuretools[autonormalize]) (2.4.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.4.0->featuretools[autonormalize]) (2022.7.1)
Requirement already satisfied: importlib-resources>=5.10.0 in /usr/local/lib/python3.9/dist-packages (from woodwork[dask]>=0.18.0->featuretools[autonormalize]) (5.12.0)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.9/dist-packages (from woodwork[dask]>=0.18.0->featuretools[autonormalize]) (1.2.2)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from importlib-resources>=5.10.0->woodwork[dask]>=0.18.0->featuretools[autonormalize]) (3.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil->holidays>=0.13->featuretools[autonormalize]) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.22->woodwork[dask]>=0.18.0->featuretools[autonormalize]) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.22->woodwork[dask]>=0.18.0->featuretools[autonormalize]) (3.1.0)
Requirement already satisfied: heapdict in /usr/local/lib/python3.9/dist-packages (from zict>=0.1.3->distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (1.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2->distributed!=2022.10.1,>=2022.2.0->featuretools[autonormalize]) (2.1.2)
Installing collected packages: woodwork, featuretools, autonormalize
Successfully installed autonormalize-2.0.1 featuretools-1.24.0 woodwork-0.22.0

In [119]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/MesumRaza/Financial-Consumer-Complaints-Case-Study/main/Consumer_Complaints_sampled.csv')

In [106]:
df.head()

,Unnamed: 0,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,0,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761
1,1,01/30/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"VW Credit, Inc",CA,91902,NaN,NaN,Fax,02-04-2015,Closed with monetary relief,Yes,No,1217673
2,2,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"URS Holding, LLC",CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283760
3,3,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761
4,4,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761

In [120]:
state_factor=pd.factorize(df.State)
df['state_id']=state_factor[0]+1
df.drop(['State'], axis=1)

,Unnamed: 0,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,state_id
0,0,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1
1,1,01/30/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"VW Credit, Inc",91902,NaN,NaN,Fax,02-04-2015,Closed with monetary relief,Yes,No,1217673,1
2,2,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"URS Holding, LLC",93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283760,1
3,3,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1
4,4,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53195,53195,05-06-2016,Student loan,Non-federal student loan,Dealing with my lender or servicer,Trouble with how payments are handled,"On XXXX XXXX 2016, I received a statement from...",Company has responded to the consumer and the ...,Bank of America,661XX,NaN,Consent provided,Web,05-06-2016,Closed with explanation,Yes,No,1913788,43
53196,53196,09/14/2016,Student loan,Non-federal student loan,Dealing with my lender or servicer,Trouble with how payments are handled,I had deferred payments set up while I was goi...,NaN,"Navient Solutions, Inc.",956XX,NaN,Consent provided,Web,09/14/2016,Closed with explanation,Yes,NaN,2112466,1
53197,53197,06-08-2016,Student loan,Non-federal student loan,Dealing with my lender or servicer,Trouble with how payments are handled,NaN,Company believes it acted appropriately as aut...,Sallie Mae,20002,NaN,Consent not provided,Web,06-08-2016,Closed with explanation,Yes,No,1960826,35
53198,53198,02/27/2016,Student loan,Non-federal student loan,Dealing with my lender or servicer,Trouble with how payments are handled,I signed up for auto payment on my Sallie Mae ...,Company believes it acted appropriately as aut...,Sallie Mae,200XX,NaN,Consent provided,Web,03-01-2016,Closed with explanation,Yes,Yes,1807401,35
53199,53199,02-01-2016,Student loan,Non-federal student loan,Dealing with my lender or servicer,Trouble with how payments are handled,NaN,NaN,AES/PHEAA,44646,NaN,Consent not provided,Web,02-01-2016,Closed with explanation,Yes,No,1766014,20

In [108]:
df.head()

,Unnamed: 0,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,state_id
0,0,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1
1,1,01/30/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"VW Credit, Inc",CA,91902,NaN,NaN,Fax,02-04-2015,Closed with monetary relief,Yes,No,1217673,1
2,2,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"URS Holding, LLC",CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283760,1
3,3,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1
4,4,03/16/2015,Debt collection,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1

In [121]:
state_df=pd.DataFrame({'state_id':range(1,state_factor[1].size+1),'state_name':state_factor[1]})

In [110]:
state_df

    state_id state_name
0          1         CA
1          2         KY
2          3         NC
3          4         IA
4          5         IL
5          6         FL
6          7         WA
7          8         TX
8          9         CT
9         10         IN
10        11         MI
11        12         SC
12        13         NY
13        14         GA
14        15         MO
15        16         MN
16        17         CO
17        18         MD
18        19         NJ
19        20         OH
20        21         TN
21        22         PA
22        23         MA
23        24         AZ
24        25         WV
25        26         LA
26        27         RI
27        28         VA
28        29         NV
29        30         MS
30        31         VT
31        32         UT
32        33         OR
33        34         AL
34        35         DC
35        36         NH
36        37         HI
37        38         WI
38        39         ID
39        40         NM
40        41         ME
41        42         DE
42        43         KS
43        44         VI
44        45         AK
45        46         OK
46        47         PR
47        48         AR
48        49         MT
49        50         NE
50        51         ND
51        52         SD
52        53         AE
53        54         WY
54        55         FM
55        56         GU
56        57         AP
57        58         MH
58        59         AS

In [122]:
Product_factor=pd.factorize(df.Product)
df['Product_id']=Product_factor[0]+1
df.drop(['Product'], axis=1,inplace=True)
Product_df=pd.DataFrame({'Product_id':range(1,Product_factor[1].size+1),'Product_name':Product_factor[1]})

In [114]:
df.head()

,Unnamed: 0,Date received,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,state_id,Product_id
0,0,03/16/2015,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1,1
1,1,01/30/2015,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"VW Credit, Inc",CA,91902,NaN,NaN,Fax,02-04-2015,Closed with monetary relief,Yes,No,1217673,1,1
2,2,03/16/2015,Auto,False statements or representation,Attempted to collect wrong amount,NaN,NaN,"URS Holding, LLC",CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283760,1,1
3,3,03/16/2015,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1,1
4,4,03/16/2015,Auto,False statements or representation,Attempted to collect wrong amount,NaN,Company chooses not to provide a public response,Ally Financial Inc.,CA,93534,NaN,NaN,Fax,03/20/2015,Closed with explanation,Yes,No,1283761,1,1

In [123]:
Product_df.head()

   Product_id     Product_name
0           1  Debt collection
1           2      Payday loan
2           3     Student loan